theme: jekyll-theme-slate

url: https://troyhill.github.io/fireHydro/docs/

BASE_PATH : /fireHydro

title: Fire-Hydro risk maps

description: A tool for integrating data and mapping fire risk in Big Cypress National Preserve and Everglades National Park.

